main: io.nv.bukkit.CleanroomGenerator.CleanroomGenerator
name: ${project.artifactId}
version: '${project.version}'
api-version: '1.21'
website: '${plugin.website}'
author: '${plugin.author}'
description: '${project.description}'
load: STARTUP
